#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/home/ricardo/Downloads/gwt-2.4.0/gwt-user.jar:/home/ricardo/Downloads/gwt-2.4.0/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src formGWT.client.i18n.Texts  ;

